version: "3.9"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    restart: always
    networks:
      - kshanti
    ports:
      - "443:443"


networks:
  kshanti:
    driver: bridge