version: "3.9"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    restart: always
    networks:
      - kshanti
    ports:
      - "443:443"
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    restart: always
    networks:
    - kshanti
    env_file: .env
    volumes:
      - my-volume:/var/www/html


networks:
  kshanti:
    driver: bridge